// <auto-generated />
using DesignTimeExample.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DesignTimeExample.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20190402014454_application_v1")]
    partial class application_v1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854");

            modelBuilder.Entity("DesignTimeExample.Models.Flight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Code");

                    b.Property<int>("PassengerNumber");

                    b.Property<int>("PlaneId");

                    b.HasKey("Id");

                    b.HasIndex("PlaneId");

                    b.ToTable("Flights");
                });

            modelBuilder.Entity("DesignTimeExample.Models.Plane", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Model");

                    b.Property<int>("SeatsNumber");

                    b.HasKey("Id");

                    b.ToTable("Planes");
                });

            modelBuilder.Entity("DesignTimeExample.Models.Flight", b =>
                {
                    b.HasOne("DesignTimeExample.Models.Plane", "Plane")
                        .WithMany("Flights")
                        .HasForeignKey("PlaneId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
